---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
  #from passlib.apps import custom_app_context as pwd_context
  #hash = pwd_context.hash("somepass")
    user_passwd: '$6$rounds=656000$WCJXrIU37njsfQku$6kijczPtLQPj6eCbGQBRk0gioMfqh5IcGQ9yyDXnM9OPsH4gmrA9j6HTasfFXGK3h9NZ/gifGiIn832tHeOmk/'
    
  tasks:

  - name: Create Users group
    group:
      name: "{{ u_name }}"

  - name: Create User
    user:
      name: "{{ u_name }}"
      groups: "{{ u_name }}, docker, vboxsf"
      password: "{{ user_passwd }}"
      shell: /bin/zsh

  - name: Create Users sudoers file
    lineinfile:
      path: /etc/sudoers.d/{{ u_name }}-nopasswd
      line: "{{ u_name }} ALL=NOPASSWD: ALL"
      regexp: '{{ u_name }} ALL='
      create: yes

  - name: Create inital User resource configuration
    become: yes
    become_user: "{{ u_name }}"
    command: "/usr/local/bin/update_devbox_tags.bash --user-resource-init"

  - name: Modify Users sudoers file
    lineinfile:
      path: /etc/sudoers.d/{{ u_name }}-nopasswd
      line: "{{ u_name }} ALL=PASSWD: ALL"
      regexp: '{{ u_name }} ALL='

  - name: Ensure DisplayManager is enabled
    service:
      name: lightdm
      state: started
      enabled: yes

